name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
     - name: Set selected color
        run: echo $CR_PAT | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.TOKEN }}
    
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/pbharambe/my-image-name:latest
        
