name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: 'pb27597'
        password: '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'
    
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag my-image-name:latest
        docker push ghcr.io/pbharambe/my-image-name:latest
